import React from 'react';
import Nav from './Nav';
import Head from 'next/head';

function Layout({ children }: { children: React.ReactNode }) {
    return (
        <>
            <Head>
                <title>관리자</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nav />
            <div>{children}</div>
        </>
    );
}

export default Layout;
